site_name: "CZAN"
site_description: "CZAN is an atomic design system for Compose Multiplatform."
site_url: https://www.czan.dev/
docs_dir: "docs"

repo_name: "CZAN"
repo_url: https://github.com/Tweener/czan/

extra:
  social:
    - icon: simple/buymeacoffee
      link: https://buymeacoffee.com/vivienmahe
    - icon: fontawesome/brands/github
      link: https://github.com/Tweener/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/VivienMahe
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vivienmahe/

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "white"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "black"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - "Overview": index.md
  - "Setup": setup.md
  - "Atoms":
      - "Bars": atoms/bars.md
      - "Box": atoms/box.md
      - "Button": atoms/button.md
      - "Checkbox": atoms/checkbox.md
      - "Chip": atoms/chip.md
      - "Dialog": atoms/dialog.md
      - "Icon": atoms/icon.md
      - "Image": atoms/image.md
      - "Line": atoms/line.md
      - "Radio button": atoms/radio-button.md
      - "Search input": atoms/search-input.md
      - "Slider": atoms/slider.md
      - "SnackBar": atoms/snackbar.md
      - "Switch": atoms/switch.md
      - "Text": atoms/text.md
      - "TextField": atoms/textfield.md
  - "Molecules":
      - "CardTip": molecules/cardtip.md
      - "NumericKeyboard": molecules/numerickeyboard.md
      - "Tabs": molecules/tabs.md
  - "Organisms":
      - "Card": organisms/card.md
