name: CZAN build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: testReleaseUnitTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java JDK ${{ vars.JAVA_JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ vars.JAVA_JDK_VERSION }}'
          distribution: "zulu"

      - name: Caching Kotlin/Native tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build library
        run: ./gradlew ${{ matrix.target }}

