name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deployToVercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java JDK ${{ vars.JAVA_JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ vars.JAVA_JDK_VERSION }}'
          distribution: "zulu"

      - name: Caching Kotlin/Native tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Actualize yarn lock file
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build with Gradle
        run: ./gradlew copyDemoSamples --parallel --build-cache

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
